export const SET_INCREMENT_COUNTER = "SET_INCREMENT_COUNTER";
export const SET_DECREMENT_COUNTER = "SET_DECREMENT_COUNTER";
export const SET_RESET_COUNTER = "SET_RESET_COUNTER";

export const GET_RANDOM_NUMBER = 'GET_RANDOM_NUMBER'
export const SET_RANDOM_NUMBER = 'SET_RANDOM_NUMBER'